version: '3'

services:
  docsify:
    container_name: vlm-docs
    restart: unless-stopped
    build: .
    image: vlm-docs
    ports:
      - "3000:3000"

networks:
 default:
  external:
   name: proxy