version: '3'

services:
  docsify:
    build:
      context: .
      dockerfile: Dockerfile
    image: vlm-docs
    container_name: vlm-docs
    ports:
      - "3000:3000"
    volumes:
      - .:/docs
